altive/flutter_app_template

- .fvm/fvm_config.json
- melos.yaml
- packages/amazon_paapi/pubspec.yaml
- packages/analysis_logger/pubspec.yaml
- packages/authenticator/lib/src/authenticator.dart
- packages/authenticator/pubspec.yaml
- packages/convenient_widgets/lib/src/bubble_border.dart
- packages/convenient_widgets/pubspec.yaml
- packages/flutter_app/android/build.gradle
- packages/flutter_app/android/gradle/wrapper/gradle-wrapper.properties
- packages/flutter_app/ios/Podfile
- packages/flutter_app/ios/Podfile.lock
- packages/flutter_app/ios/Runner.xcodeproj/project.pbxproj
- packages/flutter_app/lib/util/providers/locales_provider.dart
- packages/flutter_app/lib/util/providers/locales_provider.g.dart
- packages/flutter_app/macos/Podfile.lock
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/notification_receiver/pubspec.yaml
- packages/notification_sender/pubspec.yaml
- packages/remote_parameter_fetcher/pubspec.yaml
- packages/rest_api_client/pubspec.yaml
- packages/themes/pubspec.yaml
- packages/util/pubspec.yaml
- pubspec.lock
- pubspec.yaml
> build: bump to Flutter 3.10/Dart 3.0

- packages/amazon_paapi/pubspec.yaml
- packages/analysis_logger/pubspec.yaml
- packages/authenticator/pubspec.yaml
- packages/convenient_widgets/pubspec.yaml
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/notification_receiver/pubspec.yaml
- packages/notification_sender/pubspec.yaml
- packages/remote_parameter_fetcher/pubspec.yaml
- packages/rest_api_client/pubspec.yaml
- packages/themes/pubspec.yaml
- packages/util/pubspec.yaml
- pubspec.yaml
closes #208 
- sdk: ">=3.0.0 <4.0.0" を `sdk: ^3.0.0` に（意味は一緒）
- `altive_lints` パッケージを v1.7.0 にアップデート
> build(pub): update to altive_lints v1.7.0

- .cspell/flutter-words.txt
- packages/flutter_app/ios/Podfile.lock
- packages/flutter_app/lib/features/user_device/model/user_device.dart
- packages/flutter_app/lib/features/user_device/model/user_device.freezed.dart
- packages/flutter_app/lib/features/user_device/user_device.dart
- packages/flutter_app/lib/features/user_device/user_device_provider.dart
- packages/flutter_app/lib/features/user_device/user_device_provider.g.dart
- packages/flutter_app/lib/main.dart
- packages/flutter_app/lib/pages/settings_page/components/settings_page_body.dart
- packages/flutter_app/macos/Podfile.lock
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
> feat: device_info_plusを使用した、OS共有のデバイス情報クラス

- Makefile
- pubspec.lock
- pubspec.yaml
closes #215 
closes #198 
- [build: Melos v3.1.0](https://github.com/altive/flutter_app_template/pull/219/commits/4374befcbc1eabad5f804ddabed1c1725b141284)
- [chore: Makefileでmelosを使用するコマンドからfvmの接頭辞を削除](https://github.com/altive/flutter_app_template/pull/219/commits/58e16ba4d7a434e6c164ca6aff7f262a0d74689b)
- [chore: Makefileにコード生成アクションを追加](https://github.com/altive/flutter_app_template/pull/219/commits/d87eee606032470cfd11f001a376074b353d887e)
なし
> chore: melos v3.1.0

- .fvm/fvm_config.json
- packages/amazon_paapi/pubspec.yaml
- packages/analysis_logger/pubspec.yaml
- packages/authenticator/pubspec.yaml
- packages/convenient_widgets/pubspec.yaml
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/notification_receiver/lib/src/notification_configurator_provider.g.dart
- packages/notification_receiver/pubspec.yaml
- packages/notification_sender/pubspec.yaml
- packages/remote_parameter_fetcher/pubspec.yaml
- packages/rest_api_client/pubspec.yaml
- packages/themes/pubspec.yaml
- packages/util/pubspec.yaml
- pubspec.lock
- pubspec.yaml
closes #224 
- Flutter 3.10.3, Dart 3.0.3
- なし
> build: Flutter 3.10.3, Dart 3.0.3

- .fvm/fvm_config.json
- packages/amazon_paapi/pubspec.yaml
- packages/analysis_logger/pubspec.yaml
- packages/authenticator/pubspec.yaml
- packages/convenient_widgets/pubspec.yaml
- packages/flutter_app/ios/Runner.xcodeproj/project.pbxproj
- packages/flutter_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/flutter_app/lib/pages/account/components/account_page_body.dart
- packages/flutter_app/lib/pages/riverpod_example_page/async_notifier_provider_page/async_notifier_provider_page.dart
- packages/flutter_app/lib/pages/riverpod_example_page/notifier_provider_page/notifier_provider_page.dart
- packages/flutter_app/lib/pages/riverpod_example_page/state_notifier_provider_page/state_notifier_provider_page.dart
- packages/flutter_app/lib/pages/settings_page/components/settings_page_body.dart
- packages/flutter_app/lib/pages/splash/splash_page.dart
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/notification_receiver/pubspec.yaml
- packages/notification_sender/pubspec.yaml
- packages/remote_parameter_fetcher/pubspec.yaml
- packages/rest_api_client/lib/src/dio_client.dart
- packages/rest_api_client/pubspec.yaml
- packages/themes/pubspec.yaml
- packages/util/pubspec.yaml
- pubspec.lock
- pubspec.yaml
> build: Flutter 3.13

- .github/workflows/flutter-app-code-check-for-ignore-files.yml
- .github/workflows/flutter-app-code-check.yml
- .github/workflows/pod-install-for-dependabot.yaml
- melos.yaml
> chore: improve flutter check actions

- packages/flutter_app/lib/environment/src/flavor_provider.g.dart
- packages/flutter_app/lib/features/theme_selector/theme_selector_provider.g.dart
- packages/flutter_app/lib/features/user_device/user_device_provider.g.dart
- packages/flutter_app/lib/features/validator/validator_provider.g.dart
- packages/flutter_app/lib/package_adaptor/analysis_logger/analysis_logger_provider.g.dart
- packages/flutter_app/lib/pages/riverpod_example_page/async_notifier_provider_page/async_notifier_provider_page.g.dart
- packages/flutter_app/lib/pages/riverpod_example_page/namespace_provider_page/namespace_provider_page.g.dart
- packages/flutter_app/lib/pages/riverpod_example_page/notifier_provider_page/notifier_provider_page.g.dart
- packages/flutter_app/lib/pages/riverpod_example_page/stream_provider_page.dart/stream_provider_page.g.dart
- packages/flutter_app/lib/pages/top_level_tab/top_level_tab_state_provider.g.dart
- packages/flutter_app/lib/router/router_provider.g.dart
- packages/flutter_app/lib/util/providers/app_lifecycle_state_provider.g.dart
- packages/flutter_app/lib/util/providers/locales_provider.g.dart
- packages/flutter_app/lib/util/providers/navigator_key_provider.g.dart
- packages/flutter_app/lib/util/providers/package_info_provider.g.dart
- packages/flutter_app/lib/util/providers/shared_preferences_provider.g.dart
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- 不要なdependency_overridesを削除
- bump Riverpod to latest versions
> build: bump Riverpod to latest versions

- .fvm/fvm_config.json
- packages/amazon_paapi/pubspec.yaml
- packages/analysis_logger/pubspec.yaml
- packages/authenticator/pubspec.yaml
- packages/convenient_widgets/pubspec.yaml
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/notification_receiver/pubspec.yaml
- packages/notification_sender/pubspec.yaml
- packages/remote_parameter_fetcher/pubspec.yaml
- packages/rest_api_client/pubspec.yaml
- packages/themes/pubspec.yaml
- packages/util/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- Flutter 3.13.4
- Dart 3.1.2
- なし
> build: bump Flutter/Dart to 3.13.4/3.1.2

- .fvm/fvm_config.json
- packages/flutter_app/ios/Podfile.lock
- packages/flutter_app/macos/Podfile.lock
> build: CocoaPodsとFlutterのバージョンを最新化

- packages/flutter_app/macos/Runner/DebugProfile.entitlements
- packages/flutter_app/macos/Runner/Release.entitlements
Added the ability to access macOS files.
https://pub.dev/packages/image_picker#macos-installation
> Add read-only file access entitlements for macOS

- .vscode/settings.json
- To follow strict JSON format, Remove comments and trailing comma from settings.json
- FVM 3.0 uses strict JSON
> style: Remove comments and trailing comma from settings.json

- .github/dependabot.yml
- We have used grouped to allow pull requests to be created together to some extent.
-
> ci: Update dependabot configuration

- packages/flutter_app/.gitignore
- packages/flutter_app/android/app/build.gradle
- packages/flutter_app/ios/Runner.xcodeproj/project.pbxproj
- packages/flutter_app/macos/Runner.xcodeproj/project.pbxproj
- [refactor: dart-define for Android](https://github.com/altive/flutter_app_template/commit/4b43e0cb7e2962c59c2403156864aec4de20d5a3)
- [chore: move GoogleService-Info.plist file reference to Runner](https://github.com/altive/flutter_app_template/commit/675facac46daba4a51c84dc1adb8a218300d498d)
-
> refactor: Improve dart define from file

- packages/flutter_app/dart_defines/dev.env
- Remove unnecessary trailing commas
> fix: Fix googleReversedClientId in dev.env file

- .vscode/settings.json
- melos.yaml
> chore: Remove flutter sdk from melos

- .github/actions/setup_flutter/action.yml
- Update Flutter FVM config action from v1 to v2
-
> ci: Update Flutter FVM config action to v2

- melos.yaml
- packages/analysis_logger/pubspec.yaml
- packages/authenticator/pubspec.yaml
- packages/convenient_widgets/pubspec.yaml
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/notification_receiver/pubspec.yaml
- packages/notification_sender/pubspec.yaml
- packages/remote_parameter_fetcher/pubspec.yaml
- packages/themes/pubspec.lock
- packages/themes/pubspec.yaml
- packages/util/pubspec.yaml
- pubspec.lock
- pubspec.yaml
> build: Update SDK versions to 3.3.0

- .github/dependabot.yml
- `build_runner` が必要なグループに追加
- `slang-dependencies` グループを追加
- `go-router-dependencies` グループを追加
-
> ci: build_runnerを絡めるGroupを追加

- packages/flutter_app/lib/flutter_app.dart
- packages/themes/lib/src/altive_theme/altive_dark_color_scheme.dart
- packages/themes/lib/src/altive_theme/altive_theme.dart
- packages/themes/lib/src/altive_theme/app_text_theme.dart
- packages/themes/lib/src/altive_theme/dark_color_scheme.dart
- packages/themes/lib/src/altive_theme/dark_theme_data.dart
- packages/themes/lib/src/altive_theme/light_color_scheme.dart
- packages/themes/lib/src/altive_theme/light_theme_data.dart
- I have Renamed this repository template to make it easier to start using it when you copy it!
> chore: Improve theme data and color scheme

- .github/workflows/flutter-app-code-check.yml
- melos.yaml
- packages/flutter_app/ios/Podfile.lock
- packages/flutter_app/lib/gen/strings.g.dart
- packages/flutter_app/macos/Podfile.lock
- packages/flutter_app/pubspec.lock
- packages/flutter_app/test/pages/riverpod_example_page/async_notifier_provider_page/async_notifier_provider_page_test.mocks.dart
- pubspec.lock
- Refactor scripts in melos.yaml
- Remove `melos run analyze/format` as it was added as a built-in command.
- Update dependencies with `melos bootstrap` and `melos run pod`
- Update generated files with `melos run gen`
-
> refactor: Refactor scripts in melos.yaml

- .github/dependabot.yml
- melos.yaml
- packages/flutter_app/ios/Podfile.lock
- packages/flutter_app/macos/Podfile.lock
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- Update dependencies
- Update dependabot schedules
-
> build: Update dependencies and dependabot

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge.yaml
- https://dev.classmethod.jp/articles/github-dependabot-auto-merge/
- Add Dependabot auto-merge workflow
- Use `directories` from dependabot public beta
-
> ci: Add Dependabot Automatic merge workflow

- .github/workflows/dependabot-auto-merge.yaml
- Fix merge type
- https://github.com/altive/flutter_app_template/actions/runs/8999134759/job/24720692805
-
> chore: Update Dependabot auto-merge workflow to use squash merge

- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- Remove unused package dependency
> build(deps): remove modal_bottom_sheet dependency

- .github/actions/deploy_ios_app/action.yml
- Fix Dart-defines file path
-
> ci: Fix Dart-defines file path

- packages/flutter_app/ios/prod/ExportOptions.plist
- packages/flutter_app/ios/prod/UploadOptions.plist
- packages/flutter_app/ios/stg/ExportOptions.plist
- packages/flutter_app/ios/stg/UploadOptions.plist
- #393
- Fix ExportOptions.plist
- Create UploadOptions.plist
-
> ci: Fix ExportOptions.plist and Add UploadOptions.plist

- .cspell/project-words.txt
- .vscode/settings.json
- Change cSpell words group from app to project
-
> chore: Change cSpell words group from app to project

- melos.yaml
- packages/convenient_widgets/lib/gen/assets.gen.dart
- packages/flutter_app/lib/gen/assets.gen.dart
- [chore: Remove Melos.command.bootstrap.dependencies/dev_dependencies](https://github.com/altive/flutter_app_template/pull/429/commits/f5301b69294637f82b4184087cb893c812305b50)
- Add `build_runner build` diffs (FlutterGen)
- 
| Before | After |
|--------|--------|
> chore: Remove Melos.command.bootstrap.dependencies/dev_dependencies

- .cspell/flutter-words.txt
- .github/actions/upload_android_app/action.yml
- .github/workflows/upload-production-android-app.yaml
- .github/workflows/upload-staging-android-app.yaml
- packages/flutter_app/README.md
- Add secrets to this repository
- KEY_ALIAS
- KEY_PASSWORD
- STORE_PASSWORD
- UPLOAD_KEYSTORE_JKS
- Verify operation after merging!
> [!NOTE]
> ci: Add workflow files for Android app uploading

- .github/dependabot.yml
none.
- Use wildcard in dependabot.yml directories.
- 
> [!NOTE]
> refactor: Use wildcard in dependabot.yml directories

- .cspell/framework-words.txt
- .vscode/settings.json
none.
- Rename flutter-words to framework-words
- Includes terms for frameworks other than Flutter
> [!NOTE]
> chore: Rename flutter-words to framework-words

- packages/flutter_app/README.md
- packages/flutter_app/lib/router/app_routes.dart
- packages/flutter_app/lib/router/app_routes.g.dart
- packages/flutter_app/lib/router/branches/branches.dart
- packages/flutter_app/lib/router/branches/dashboard_routes.dart
- packages/flutter_app/lib/router/branches/explore_routes.dart
- packages/flutter_app/lib/router/branches/home_routes.dart
- packages/flutter_app/lib/router/branches/post_routes.dart
- packages/flutter_app/lib/router/branches/settings_routers.dart
- packages/flutter_app/lib/router/router.dart
- packages/flutter_app/lib/router/router_provider.dart
- packages/flutter_app/lib/router/router_provider.g.dart
none.
- Commented on each file.
- For some reason, I can't see the event submission in DebugView in this project...
> [!NOTE]
> refactor: Update GoRouter routes

- .github/workflows/flutter-app-code-check.yml
- packages/flutter_app/analysis_options.yaml
- packages/flutter_app/lib/pages/home_page/home_page.dart
- packages/flutter_app/lib/pages/riverpod_example_page/util/fake_dio.dart
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/util/analysis_options.yaml
> build(deps): Update altive_lints to 1.11.1

- packages/flutter_app/ios/Runner/AppDelegate.swift
- packages/flutter_app/macos/Runner/AppDelegate.swift
- packages/flutter_app/pubspec.lock
None.
- Fix build failure on Android
- `flutter pub upgrade win32`
- Add iOS building diff
- 
> [!NOTE]
---
https://github.com/jonataslaw/get_cli/issues/263
> ci: Fix build failure on Android

- packages/flutter_app/analysis_options.yaml
- packages/flutter_app/lib/pages/riverpod_example_page/async_notifier_provider_page/async_notifier_provider_page.dart
- packages/flutter_app/lib/pages/riverpod_example_page/notifier_provider_page/notifier_provider_page.dart
- packages/flutter_app/lib/pages/riverpod_example_page/state_notifier_provider_page/state_notifier_provider_page.dart
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- closes #461 
- prefer_clock_now to true
- 
> [!NOTE]
> chore: Set "prefer_clock_now" to true

- .gitignore
- Makefile
- Deleted Mason's relevant description since it is not used.
> [!NOTE]
> chore: Remove mason

- packages/flutter_app/android/app/build.gradle
- Migrate Android Firebase KTX modules to main modules
- docs: https://firebase.google.com/docs/android/kotlin-migration
I have confirmed that the Android application can be launched.
> [!NOTE]
> ci: Migrate Android Firebase KTX modules to main modules

- .vscode/riverpod.code-snippets
- Fix Riverpod code snippets
- I updated the snippet to match Riverpod 2.6.1!
- None
> [!NOTE]
> chore: Fix Riverpod code snippets

- packages/flutter_app/macos/Podfile.lock
- packages/flutter_app/pubspec.lock
- packages/flutter_app/pubspec.yaml
- packages/pub_dev_api_client/lib/src/models/get_package_details_response_body.dart
- packages/pub_dev_api_client/lib/src/models/get_package_details_response_body.freezed.dart
- packages/pub_dev_api_client/lib/src/models/get_searched_packages_response_body.dart
- packages/pub_dev_api_client/lib/src/models/get_searched_packages_response_body.freezed.dart
- packages/pub_dev_api_client/lib/src/models/latest_package_release.dart
- packages/pub_dev_api_client/lib/src/models/latest_package_release.freezed.dart
- packages/pub_dev_api_client/lib/src/models/package_name.dart
- packages/pub_dev_api_client/lib/src/models/package_name.freezed.dart
- packages/pub_dev_api_client/lib/src/models/package_pubspec.dart
- packages/pub_dev_api_client/lib/src/models/package_pubspec.freezed.dart
- packages/pub_dev_api_client/pubspec.lock
- packages/pub_dev_api_client/pubspec.yaml
- packages/widget_catalog/pubspec.yaml
- Update Podfile.lock
- Changed internal widget dependency from path to version
- Locally it is changed to the path in pubspec_overrides.yaml
- The local package version has been unified to v1.0.0
- Remove flutter dependency from `pub_dev_api_client`
- Because it was only used in the flutter/foundation import.
- Run `build_runner build` and commit diff
- 
> [!NOTE]
> chore: Fix several issues

- packages/flutter_app/ios/Podfile.lock
- packages/flutter_app/macos/Podfile.lock
- packages/widget_catalog/macos/Podfile.lock
> build(deps): update Podfile.lock files

- .github/workflows/dependabot-auto-merge.yaml
- Auto-Approve for dependabot PR
- Doc: https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
> [!NOTE]
> ci: Enable Auto-Approve for dependabot PR
